# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0ee783cc-5e5d-438c-bae4-04a965adb579'
  azureSubscriptionConnection: 'a8d1684e-40b9-430d-9b63-ec483598d2cb'
  imageRepository: 'backendwebapi'
  containerRegistry: 'backendwebapi.azurecr.io'
  containerAppName: 'backend-api-container'
  resourceGroup: 'VisualStudioOnline-2861540766144BF1AEA5AB50427A8E55'
  dockerfilePath: '$(Build.SourcesDirectory)/src/Web.API/Dockerfile'
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: '$(Build.Repository.LocalPath)'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
- stage: Deploy
  displayName: Deploy Stage
  dependsOn: Build
  jobs:
    - job: Deploy
      displayName: Deploy to ACA
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - task: AzureCLI@2
          displayName: Update Container App Image
          inputs:
            azureSubscription: $(azureSubscriptionConnection)
            scriptType: 'bash'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az containerapp update \
                --name $(containerAppName) \
                --resource-group $(resourceGroup) \
                --image $(dockerRegistryServiceConnection)/$(imageRepository):$(tag)
