<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ProjectName>Application</ProjectName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="MediatR" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Messaging\" />
  </ItemGroup>

</Project>
